name: super_flutter
description: A new Flutter project.
publish_to: abdullahAlwajih
version: 0.0.7
homepage:  https://github.com/abdullahAlwajih/Super-Flutter.git

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  super_localizations:
    git:
      url: https://github.com/abdullahAlwajih/Super-Localizations.git

  super_repository:
    git:
      url: https://github.com/abdullahAlwajih/Super-Repository.git





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter:

